### PR TITLE
fix(utilities): handle block toggles - I323

### LINKED ISSUE #323: Roundtrip Ordered List
**Describe the bug**
A user cannot roundtrip the ordered list in the demo

**To Reproduce**
1. Go to the [live demo](https://accordproject-markdown-editor.netlify.com/)
2. Highlight the entire ordered list (one, two, three)
3. Deselect numbered list in the format toolbar
4. See they have turned into an incorrect bulleted list
5. Format back into a numbered list with the format toolbar
6. See further error rendering the numbers in the list

**Expected behavior**
Roundtripping lists should behave as expected.

**Screenshots**
Screen Shot 2020-04-13 at 10 03 34 AM

### PR DESCRIPTION
**Pull request by irmerk**
# Closes #323
Handle roundtrip action of toggling block types

### Changes
- Unwraps all block types
- If the selection began as not a block, wrap in the format
  - If the format is a list, wrap each child node in a `list_item`

### Flags
- N/A

### CODE REVIEW

**Comment by Michael-Grover** [comment]
Does this have any effect on the functionality from a users' perspective? I can't tell

**Comment by irmerk** [comment]
@Michael-Grover go to the [current demo](https://accordproject-markdown-editor.netlify.app/), highlight a list, toggle it on and off.

File: src/RichTextEditor/utilities/toolbarHelpers.js [hunk 1]
```diff
@@ -16,25 +18,31 @@ export const isMarkActive = (editor, format) => {
...
+  const isQuote = input => input === BLOCK_QUOTE;
+  const isListItem = input => input === LIST_ITEM;
+
+  /* Clear selection of block types */
+  Transforms.unwrapNodes(editor, { match: n => isQuote(n.type), split: true });
+  Transforms.unwrapNodes(editor, { match: n => isListItem(n.type), split: true });
+  Transforms.unwrapNodes(editor, { match: n => LIST_TYPES.includes(n.type), split: true });
+
+  if (!isActive) {
+    const formattedBlock = { type: format, children: [], data: { tight: true } };
```
Comment (DianaLease) [inline src/RichTextEditor/utilities/toolbarHelpers.js:31]: Don't we only need the `tight` property if it's a list? I don't _think_ we need it if it's a block quote.

Comment (irmerk) [reply src/RichTextEditor/utilities/toolbarHelpers.js]: I didn't see a change when doing so, but I made this be an empty object if it's a block quote.
